minimum_pre_commit_version: "1.21"
repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.14.3
    hooks:
      - id: check-github-workflows
      - id: check-readthedocs
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: [-d relaxed]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    - id: isort
      additional_dependencies: [toml]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PYCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: (^.venv|tests)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    - id: mypy
      # for args see https://mypy.readthedocs.io/en/stable/command_line.html
      args: [
          --no-strict-optional,
          --ignore-missing-imports,
          --allow-untyped-globals
      ]
default_language_version:
    python: python3.7
